# RT-Thread building script for bridge

import os
from building import *

Import('rtconfig')

cwd   = GetCurrentDir()
list  = os.listdir(cwd)

# sim code
src	= Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('CPU', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
