import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]

src     = Split("""
main.c
""")

if GetDepend(['PKG_USING_PERSIMMON_LIB']):
    src += ['app_launch_cmd.c']
    src += ['app_management_cmd.c']
    # src += ['update_data.c']

if GetDepend(['RT_USING_DFS']):
    src += ['mnt.c']

# if GetDepend(['BSP_USING_UDBD']):
#     src += ['udbd.c']
#     src += ['udbd_install.c']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
