import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

src = Split("""
peripheral/rtl876x_io_dlps.c
peripheral/rtl876x_rcc.c
peripheral/rtl876x_gpio.c
peripheral/rtl876x_rtc.c
peripheral/rtl876x_nvic.c
peripheral/rtl876x_pinmux.c
peripheral/rtl876x_gdma.c
peripheral/rtl876x_tim.c
peripheral/rtl876x_if8080.c
peripheral/rtl876x_adc.c
""")

if GetDepend(['RT_USING_SERIAL']):
    src += ['peripheral/rtl876x_uart.c']

#if GetDepend(['BSP_USING_I2C']):
#    src += ['peripheral/rtl876x_i2c.c']

path = [cwd,
        cwd + '/../inc/peripheral']
		
src += Split("""
rtl876x/overlay_mgr.c
rtl876x/system_rtl876x.c
""")



if rtconfig.CROSS_TOOL == 'gcc':
	src +=['rtl876x/arm/startup_rtl876x_gcc.s']
elif rtconfig.CROSS_TOOL == 'iar':
    src +=['rtl876x/arm/startup_rtl876x_iar.s']
elif rtconfig.CROSS_TOOL == 'keil':
    src +=['rtl876x/arm/startup_rtl876x.s']	
	

group = DefineGroup('RTK_BSP', src, depend = [''], CPPPATH = path)

Return('group')
