import rtconfig
from building import *

cwd = GetCurrentDir()

src = Split("""
dlps_app.c
""")

if GetDepend(['BSP_USING_DLPS']):
    src += ['dlps_app.c']

CPPPATH = [cwd]

group = DefineGroup('DLSP', src, depend=['BSP_USING_DLPS'], CPPPATH=CPPPATH)

Return('group')
