import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

src = Split("""
""")

if GetDepend(['BSP_USING_BLE']):
    src +=  Split("""
	profile/server/bas.c
	profile/server/dis.c
	""")
	


group = DefineGroup('RTK_BSP', src, depend = [''], CPPPATH =[''])

Return('group')
